hyperskill_project:
  id: 173
  ide_files: https://stepik.org/media/attachments/lesson/512120/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 893
  step: 12802
  is_completed: false
- id: 894
  step: 12803
  is_completed: false
- id: 895
  step: 12804
  is_completed: false
- id: 896
  step: 12805
  is_completed: false
